env_name: "racetrack-v0"
save_data_flag: true
control_type: "classic" # classic, rl_based
controller_type: "pid"
model_type: "sac"
sac_model_filepth: "sota_model/racetrack-v0_sac/model.zip"

plot_target_signal: {
  front_angle: [
    lat_cmd,
    feedforward,
    feedback,
  ],
  speed: [
    vehicle_speed,
  ],
  lat_err: [
    lat_err,
  ],
  heading_err: [
    heading_err,
  ],
  curvature: [
    curvature,
  ],
  s: [
    s_traveled,
  ]
}

train_data_target_signals: [
  "control_cmd:target_front_angle",
  # "control_cmd:target_acc",
  "vehicle_state:front_angle",
  # "vehicle_state:acc",
  "vehicle_state:v",
  "vehicle_state:curvature",
  "control_debug:lat_error",
  "control_debug:heading_error",
  "vehicle_state:heading_rate",
]

